
---
# install_docker.yml
- name: Install prerequisites for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: yes
  delegate_to: "{{ ip_address }}"

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  delegate_to: "{{ ip_address }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
  become: yes
  delegate_to: "{{ ip_address }}"

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  become: yes
  delegate_to: "{{ ip_address }}"

- name: Ensure Docker is started
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  delegate_to: "{{ ip_address }}"
