---
- name: Update MikroTik Packages
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Update MikroTik package list
      community.routeros.routeros_command:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - /system/package/update/download
      
    - name: Install MikroTik packages
      community.routeros.routeros_command:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - /system/package/update/install
