---
- name: Check and Update MikroTik Router OS
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Check for OS updates
      ansible.builtin.shell: |
        /system package update download
      register: update_download

    - name: Install OS updates
      ansible.builtin.shell: |
        /system package update install
      when: update_download.rc == 0
      register: update_install

    - name: Display update results
      debug:
        var: update_install.stdout_lines
