---
- name: Check and update MikroTik RouterOS using SSH
  hosts: mikrotik
  gather_facts: no
  vars:
    routeros_user: "admin"
    routeros_password: "awt_aom12"
  tasks:
    - name: Check for available updates with increased SSH timeout
      raw: |
        /system package update check-for-updates
      register: update_status
      ignore_errors: yes
      changed_when: false
      retries: 3
      delay: 10

    - name: Display update status
      debug:
        var: update_status.stdout

    - name: Download the new update if available
      raw: |
        /system package update download
      when: "'New version' in update_status.stdout"

    - name: Reboot to apply the update if needed
      raw: |
        /system reboot
      when: "'New version' in update_status.stdout"
