---
- name: Stop Docker container "watchtower"
  hosts: docker
  become: yes
  tasks:
    - name: Stop the Docker container "watchtower"
      community.docker.docker_container:
        name: watchtower
        state: started
